# SPDX-FileCopyrightText: Copyright 2026 Cathy J. Fitzpatrick <cathy@cathyjf.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Run Unix tests
description: Configure, build, and run Unix tests

inputs:
  path:
    description: Source path to use for configuration, building, and testing
    required: true
  preset:
    description: Preset to supply to CMake and CTest
    required: true

runs:
  using: composite
  steps:
    - name: Test the '${{ inputs.preset }}' preset under '${{ inputs.path }}'
      shell: bash
      env:
        SOURCE_PATH: ${{ inputs.path }}
        PRESET: ${{ inputs.preset }}
      run: |
        [[ $(uname) == 'Darwin' ]] || {
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          [[ $PRESET != 'unix' ]] || {
            llvm_dir=$(brew --prefix llvm)
            export LDFLAGS=-L${llvm_dir}/lib
            export LD_LIBRARY_PATH=${llvm_dir}/lib:$LD_LIBRARY_PATH
          }
        }
        build_dir=$(mktemp -d "${RUNNER_TEMP}/${PRESET}.XXXXXX")
        cmake -B "$build_dir" -S "$SOURCE_PATH" --preset "$PRESET"
        cmake --build "$build_dir" --preset "$PRESET"
        ctest --test-dir "$build_dir" \
          --presets-file "${SOURCE_PATH}/CMakePresets.json" \
          --preset "$PRESET"
