# SPDX-FileCopyrightText: Copyright 2026 Cathy J. Fitzpatrick <cathy@cathyjf.com>
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  windows:
    name: windows-${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x64
            runner: windows-2025-vs2026
            builder_runner: ubuntu-26.04
          - architecture: arm64
            runner: windows-11-vs2026-arm
            builder_runner: ubuntu-26.04-arm
    uses: $/.github/workflows/windows-ci-suite.yml
    with:
      architecture: ${{ matrix.architecture }}
      runner: ${{ matrix.runner }}
      builder_runner: ${{ matrix.builder_runner }}

  unix:
    name: unix-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: mac
            runner: xcode-27
          - os: gnu-linux
            runner: ubuntu-latest
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        background: true
        id: checkout

      - uses: $/.github/actions/remove-ipv6-addresses
        with:
          os: ${{ matrix.os }}

      - name: Acquire toolchains
        run: |
          packages=(llvm lld gcc)
          [[ $(uname) == 'Darwin' ]] || {
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            # Note: glibc must be installed before gcc.
            packages=(cmake glibc "${packages[@]}")
          }
          HOMEBREW_NO_ASK=1 brew install "${packages[@]}"

      - name: Wait for checkout
        wait: checkout

      - name: Acquire dependencies for the remaining macOS tests
        id: additional-dependencies
        if: matrix.os == 'mac'
        background: true
        run: |
          HOMEBREW_NO_ASK=1 brew install perl samba grpc
          perl_bin_dir=$(brew --prefix perl)/bin
          export PATH="${perl_bin_dir}:$PATH"
          printf '%s\n' "$perl_bin_dir" >> "$GITHUB_PATH"
          cpan ExtUtils::MakeMaker Parse::Yapp
          . src/wsl/install-pidl.sh

      - name: Run terminal tests with the LLVM/libc++ toolchain
        uses: $/.github/actions/run-unix-tests
        background: true
        with:
          path: src/terminal
          preset: unix

      - name: Run terminal tests with the GCC/libstdc++ toolchain
        uses: $/.github/actions/run-unix-tests
        background: true
        with:
          path: src/terminal
          preset: unix-gcc

      - name: Wait for acquisition of remaining macOS dependencies
        wait: additional-dependencies

      - name: Run the remaining macOS tests
        if: matrix.os == 'mac'
        uses: $/.github/actions/run-unix-tests
        with:
          path: src/unix
          preset: release

      - name: Wait for completion
        wait-all:
